/**
 * Wallet Service
 * Handles integration with Apple Wallet and Google Wallet
 */

export interface PassData {
  userName: string;
  memberId?: string;
  qrCodeData?: string;
  cardTitle?: string;
  cardDescription?: string;
}

export interface WalletError {
  message: string;
  code?: string;
  platform?: 'apple' | 'google';
}

/**
 * Generate a unique member ID based on user name
 */
const generateMemberId = (userName: string): string => {
  const timestamp = Date.now();
  const hash = userName.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
  return `CMUS-${hash.toString(36).toUpperCase()}-${timestamp.toString(36).toUpperCase()}`;
};

/**
 * Generate QR code data for the loyalty card
 */
const generateQRCodeData = (memberId: string, userName: string): string => {
  return JSON.stringify({
    id: memberId,
    name: userName,
    type: 'loyalty',
    timestamp: Date.now()
  });
};

/**
 * Add pass to Apple Wallet
 * This function triggers the download of a .pkpass file
 * The file should be generated by a backend API endpoint
 */
export const addToAppleWallet = async (passData: PassData): Promise<void> => {
  try {
    // Get the API endpoint from environment variables
    const apiEndpoint = import.meta.env.VITE_APPLE_WALLET_API_ENDPOINT;
    
    if (!apiEndpoint) {
      throw new Error('Apple Wallet API endpoint is not configured. Please set VITE_APPLE_WALLET_API_ENDPOINT in your .env file.');
    }

    // Prepare pass data for the backend
    const memberId = passData.memberId || generateMemberId(passData.userName);
    const qrCodeData = passData.qrCodeData || generateQRCodeData(memberId, passData.userName);

    const requestBody = {
      userName: passData.userName,
      memberId,
      qrCodeData,
      cardTitle: passData.cardTitle || 'Coffee Rewards',
      cardDescription: passData.cardDescription || 'Loyalty Member Card'
    };

    // Fetch the .pkpass file from the backend
    const response = await fetch(apiEndpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Failed to generate Apple Wallet pass: ${response.status} ${errorText}`);
    }

    // Get the .pkpass file as a blob
    const blob = await response.blob();
    
    // Create a temporary URL for the blob
    const url = window.URL.createObjectURL(blob);
    
    // Create a temporary anchor element to trigger download
    const link = document.createElement('a');
    link.href = url;
    link.download = 'loyalty-card.pkpass';
    document.body.appendChild(link);
    link.click();
    
    // Clean up
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);

    // On iOS Safari, the .pkpass file will automatically open in Wallet app
    // For other platforms, the file will be downloaded
    
  } catch (error) {
    const walletError: WalletError = {
      message: error instanceof Error ? error.message : 'Unknown error occurred while adding to Apple Wallet',
      code: 'APPLE_WALLET_ERROR',
      platform: 'apple'
    };
    throw walletError;
  }
};

/**
 * Add pass to Google Wallet
 * Uses Google Wallet API to create and save a loyalty card
 */
export const addToGoogleWallet = async (passData: PassData): Promise<void> => {
  try {
    // Check if Google Wallet API is available
    if (typeof window === 'undefined' || !window.google || !window.google.wallet) {
      // Load Google Wallet API script if not available
      await loadGoogleWalletScript();
    }

    const issuerId = import.meta.env.VITE_GOOGLE_WALLET_ISSUER_ID;
    const classId = import.meta.env.VITE_GOOGLE_WALLET_CLASS_ID || 'loyalty_card_class';
    const apiKey = import.meta.env.VITE_GOOGLE_WALLET_API_KEY;

    if (!issuerId || !apiKey) {
      throw new Error('Google Wallet credentials are not configured. Please set VITE_GOOGLE_WALLET_ISSUER_ID and VITE_GOOGLE_WALLET_API_KEY in your .env file.');
    }

    const memberId = passData.memberId || generateMemberId(passData.userName);
    const qrCodeData = passData.qrCodeData || generateQRCodeData(memberId, passData.userName);

    // Create the loyalty object for Google Wallet
    const loyaltyObject = {
      id: `${issuerId}.${memberId}`,
      classId: `${issuerId}.${classId}`,
      state: 'ACTIVE',
      heroImage: {
        sourceUri: {
          uri: import.meta.env.VITE_GOOGLE_WALLET_HERO_IMAGE_URL || ''
        }
      },
      textModulesData: [
        {
          header: 'Member Name',
          body: passData.userName,
          id: 'member_name'
        },
        {
          header: 'Member ID',
          body: memberId,
          id: 'member_id'
        }
      ],
      barcode: {
        type: 'QR_CODE',
        value: qrCodeData,
        alternateText: memberId
      },
      accountName: passData.userName,
      accountId: memberId,
      loyaltyPoints: {
        label: 'Points',
        balance: {
          string: '0'
        }
      }
    };

    // Create the pass class if it doesn't exist (this would typically be done server-side)
    const loyaltyClass = {
      id: `${issuerId}.${classId}`,
      issuerName: import.meta.env.VITE_GOOGLE_WALLET_ISSUER_NAME || 'Coffee Rewards',
      reviewStatus: 'UNDER_REVIEW',
      programName: passData.cardTitle || 'Coffee Rewards',
      programLogo: {
        sourceUri: {
          uri: import.meta.env.VITE_GOOGLE_WALLET_LOGO_URL || ''
        }
      }
    };

    // Use Google Wallet API to save the pass
    // Note: This requires the Google Wallet API JavaScript library
    if (window.google && window.google.wallet && window.google.wallet.objects) {
      await window.google.wallet.objects.save({
        'loyaltyObjects': [loyaltyObject]
      });
    } else {
      // Fallback: Use the REST API endpoint if JavaScript API is not available
      const apiEndpoint = import.meta.env.VITE_GOOGLE_WALLET_API_ENDPOINT;
      
      if (!apiEndpoint) {
        throw new Error('Google Wallet API endpoint is not configured. Please set VITE_GOOGLE_WALLET_API_ENDPOINT in your .env file.');
      }

      const response = await fetch(apiEndpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${apiKey}`
        },
        body: JSON.stringify({
          loyaltyObject,
          loyaltyClass
        })
      });

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`Failed to create Google Wallet pass: ${response.status} ${errorText}`);
      }

      const result = await response.json();
      
      // Open the save URL in Google Wallet
      if (result.saveUrl) {
        window.location.href = result.saveUrl;
      } else {
        throw new Error('No save URL returned from Google Wallet API');
      }
    }
    
  } catch (error) {
    const walletError: WalletError = {
      message: error instanceof Error ? error.message : 'Unknown error occurred while adding to Google Wallet',
      code: 'GOOGLE_WALLET_ERROR',
      platform: 'google'
    };
    throw walletError;
  }
};

/**
 * Load Google Wallet API script dynamically
 */
const loadGoogleWalletScript = (): Promise<void> => {
  return new Promise((resolve, reject) => {
    if (window.google && window.google.wallet) {
      resolve();
      return;
    }

    const script = document.createElement('script');
    script.src = 'https://pay.google.com/gp/p/js/pay.js';
    script.async = true;
    script.onload = () => {
      if (window.google && window.google.wallet) {
        resolve();
      } else {
        reject(new Error('Google Wallet API failed to load'));
      }
    };
    script.onerror = () => {
      reject(new Error('Failed to load Google Wallet API script'));
    };
    document.head.appendChild(script);
  });
};

/**
 * Check if Apple Wallet is available on the current platform
 */
export const isAppleWalletAvailable = (): boolean => {
  if (typeof window === 'undefined') return false;
  
  const userAgent = window.navigator.userAgent.toLowerCase();
  const isIOS = /iphone|ipad|ipod/.test(userAgent);
  const isSafari = /safari/.test(userAgent) && !/chrome|crios|fxios/.test(userAgent);
  
  return isIOS || (isSafari && isIOS);
};

/**
 * Check if Google Wallet is available on the current platform
 */
export const isGoogleWalletAvailable = (): boolean => {
  if (typeof window === 'undefined') return false;
  
  const userAgent = window.navigator.userAgent.toLowerCase();
  const isAndroid = /android/.test(userAgent);
  
  return isAndroid || true; // Google Wallet can work on any platform via web
};

// Extend Window interface for TypeScript
declare global {
  interface Window {
    google?: {
      wallet?: {
        objects?: {
          save: (data: { loyaltyObjects: unknown[] }) => Promise<void>;
        };
      };
    };
  }
}

