/**
 * Wallet Service
 * Handles integration with Apple Wallet and Google Wallet
 */

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:3000';

export interface PassData {
  userName: string;
  memberId?: string;
  qrCodeData?: string;
  cardTitle?: string;
  cardDescription?: string;
  /** Required for Google Wallet: customer ID from signup (used by backend to build pass). */
  customerId?: string;
  /** Required for Google Wallet: restaurant ID (used by backend to build pass). */
  restaurantId?: string;
}

export interface WalletError {
  message: string;
  code?: string;
  platform?: 'apple' | 'google';
}

/**
 * Generate a unique member ID based on user name
 */
const generateMemberId = (userName: string): string => {
  const timestamp = Date.now();
  const hash = userName.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
  return `CMUS-${hash.toString(36).toUpperCase()}-${timestamp.toString(36).toUpperCase()}`;
};

/**
 * Generate QR code data for the loyalty card
 */
const generateQRCodeData = (memberId: string, userName: string): string => {
  return JSON.stringify({
    id: memberId,
    name: userName,
    type: 'loyalty',
    timestamp: Date.now()
  });
};

/**
 * Add pass to Apple Wallet
 * This function triggers the download of a .pkpass file
 * The file should be generated by a backend API endpoint
 */
export const addToAppleWallet = async (passData: PassData): Promise<void> => {
  try {
    // Get the API endpoint from environment variables
    const apiEndpoint = import.meta.env.VITE_APPLE_WALLET_API_ENDPOINT;
    
    if (!apiEndpoint) {
      throw new Error('Apple Wallet API endpoint is not configured. Please set VITE_APPLE_WALLET_API_ENDPOINT in your .env file.');
    }

    // Prepare pass data for the backend
    const memberId = passData.memberId || generateMemberId(passData.userName);
    const qrCodeData = passData.qrCodeData || generateQRCodeData(memberId, passData.userName);

    const requestBody = {
      userName: passData.userName,
      memberId,
      qrCodeData,
      cardTitle: passData.cardTitle || 'Coffee Rewards',
      cardDescription: passData.cardDescription || 'Loyalty Member Card'
    };

    // Fetch the .pkpass file from the backend
    const response = await fetch(apiEndpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Failed to generate Apple Wallet pass: ${response.status} ${errorText}`);
    }

    // Get the .pkpass file as a blob
    const blob = await response.blob();
    
    // Create a temporary URL for the blob
    const url = window.URL.createObjectURL(blob);
    
    // Create a temporary anchor element to trigger download
    const link = document.createElement('a');
    link.href = url;
    link.download = 'loyalty-card.pkpass';
    document.body.appendChild(link);
    link.click();
    
    // Clean up
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);

    // On iOS Safari, the .pkpass file will automatically open in Wallet app
    // For other platforms, the file will be downloaded
    
  } catch (error) {
    const walletError: WalletError = {
      message: error instanceof Error ? error.message : 'Unknown error occurred while adding to Apple Wallet',
      code: 'APPLE_WALLET_ERROR',
      platform: 'apple'
    };
    throw walletError;
  }
};

/**
 * Add pass to Google Wallet
 * Calls backend to get a signed save URL, then redirects the user to add the pass.
 * Requires customerId and restaurantId in passData (provided by SuccessScreen after signup).
 */
export const addToGoogleWallet = async (passData: PassData): Promise<void> => {
  try {
    const { customerId, restaurantId } = passData;
    if (!customerId || !restaurantId) {
      throw new Error('Customer and restaurant are required to add to Google Wallet. Please complete signup first.');
    }

    const response = await fetch(`${API_BASE_URL}/api/wallet/google-pass`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ customerId, restaurantId }),
    });

    const result = await response.json().catch(() => ({}));

    if (!response.ok) {
      const message = result.message || (response.status === 503
        ? 'Google Wallet is not configured. Please try again later.'
        : result.error || `Failed to create pass (${response.status})`);
      throw new Error(message);
    }

    const saveUrl = result.data?.saveUrl;
    if (!saveUrl || typeof saveUrl !== 'string') {
      throw new Error('No save URL returned from the server.');
    }

    window.location.href = saveUrl;
  } catch (error) {
    const walletError: WalletError = {
      message: error instanceof Error ? error.message : 'Unknown error occurred while adding to Google Wallet',
      code: 'GOOGLE_WALLET_ERROR',
      platform: 'google'
    };
    throw walletError;
  }
};

/**
 * Check if Apple Wallet is available on the current platform
 */
export const isAppleWalletAvailable = (): boolean => {
  if (typeof window === 'undefined') return false;
  
  const userAgent = window.navigator.userAgent.toLowerCase();
  const isIOS = /iphone|ipad|ipod/.test(userAgent);
  const isSafari = /safari/.test(userAgent) && !/chrome|crios|fxios/.test(userAgent);
  
  return isIOS || (isSafari && isIOS);
};

/**
 * Check if Google Wallet is available on the current platform
 */
export const isGoogleWalletAvailable = (): boolean => {
  if (typeof window === 'undefined') return false;
  
  const userAgent = window.navigator.userAgent.toLowerCase();
  const isAndroid = /android/.test(userAgent);
  
  return isAndroid || true; // Google Wallet can work on any platform via web
}

